### ISSUE TITLE
JAR not starting

### ISSUE THREAD

**Issue by ImDini** [jdleo/SMS-BOMBER#3]
I was using the python script just fine till it stopped working with error "traceback (most recent call back list:)".

So, attempted to use the jar/simple version (note I already have JRE installed because I use a different jar tool that works just fine). The SMS bomber jar doesn't start at all, just windows loading symbol and nothing. I installed 32 bit and 64 JRE (again). Still nothing sadly, not sure what else to try.

**Comment by jdleo** [comment]
The python script should be working, and I don't think I'll be able to reproduce; however, I can debug the java program. Let me try to get it fixed. I fixed a big problem a while back but I never pushed new codebase to github. I'll get back to you!

**Comment by disimoned** [comment]
Any update on the fix?

**Comment by mitya12342** [comment]
```
PS D:\Downloads> java -jar .\JohnsSMSBomber03.jar
Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problems:
        The method addActionListener(ActionListener) in the type AbstractButton is not applicable for the arguments (new ActionListener(){})
        ActionListener cannot be resolved to a type
        ActionEvent cannot be resolved to a type

        at Bomber.initialize(Bomber.java:161)
        at Bomber.<init>(Bomber.java:37)
        at Bomber$1.run(Bomber.java:24)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```
Here is java problem
